template<typename T,const int B>class bitset_chan{public:using T_T=T;static_assert(sizeof(T)*8==B,"check block width");static_assert(std::is_same  <T,                                                                                          uint64_t >  ::    value,"modify popcnt(), ctz(), clz()");public    : 
/*e*/static/**//**/inline/**//**/constexpr/**/bool/*ha*/on/*x*//**/(int/**//*z*/i/**/,T/**/x/*il*/)noexcept{/**/return/**//**/(/*     qi*/  /*   h*/(                                                                                                                 /*bnhc*//**/T(1)/**/<<i)&/*r*//**//**/         
x)!=/*cdt*//**/0/**/;/*l*/}static/**//**/inline/**//**/constexpr/**/T/*s*/prefix/**/(int/*dx*/i)noexcept/**//**/{/**/return/**/     /*kk       b*/                                                                                                                      /*r*/(i/*n*/>=B/*z*/)/**/?~/*i*//**/         
/*wf*//*s*//**//**/T(0/**//**/)/*x*/:(/**/(T(/**//*h*/1/**//**/)<<i/**//**//**/)/*dq*//**/-/*kyr*/T/**//**//**//**/(/**//**/1       ));                                                                                                                                  }static/**/inline/*c*/constexpr/**/         
T/*y*/suffix(int/**/i)noexcept{return~/**/prefix/**/(B/**/-/*sn*/i)/**/;/**/}/**//*y*/static/**/inline/**//**/constexpr/**/         T                                                                                                                                      /*mi*//**//*n*/range/**/(/*t*/int         
/*h*//*cc*//*e*//**/l/**/,/**/int/**/r/*d*//*w*/)noexcept/**/{/*i*/return/**/prefix(r)^/**/prefix(l/**/-/**/1);}static/**/                                                                                                                                                  constexpr/*dp*/int/**/popcnt/**/         
(T/*im*/x)noexcept{return/**/__builtin_popcountll(x);}static/*t*/constexpr/**/int/**/clz(T/**//**/x)/**/noexcept/**//*j*/                                                                                                                                                    {return/*i*/__builtin_clzll/**/         
(x);}/*mo*/static/**/constexpr/**/int/**//**/ctz(T/**/x)/**//*jeqa*/noexcept{return/**/__builtin_ctzll(/**//**/x)/*rl*/                                                                 ;}                                                                                    static/**/inline/*z*/constexpr         
int/**/block_id(int/*gz*/i)/**/noexcept{return/*jb*/i/**//**//B;/**/}public/**/:inline/**/T/**/submask(/**/int/**//**/                                                         /*      */                                                                                      /*msb*//**/l/**/,/**/int/**/r         
)const/*tn*/noexcept{int/*u*//**//**/bx=/**/block_id/**/(l/*s*/);assert/**/(/**/bx==block_id(r)/**/)/*e*/;/*a*/return                                                        /*o      */                                                                                        /*s*//**//**/(/**//*z*//**/b         
/*xj*//**//*p*//**//*mvturh*//**//**//*yvgz*//**//*w*//*xy*//*cra*//**//*a*/[bx]&range/**/(l-/**/bx*B+1/**//**/,/**/                                                       r-bx     *B+1                                                                                         )/**//**//**/)/*k*//*fi*/;}         
inline/**//*t*//*l*/void/**//**/trim/**/(/**/)noexcept{/*od*/b.back/**//**/(/**/)/**/&=/*t*/prefix(n/*ze*//**//*o*/                                                      %B==0     ?/**/                                                                                          /**/B/**/:n/*qu*/%/**//**/         
B)/**//**//**/;}/**//*mt*/public/*e*//**//**/:int/**/n/**/,/*t*/m/**/;/**/std::vector</*f*/T>b/**/;bitset_chan/**/                                                     /**//*     */(int                                                                                           /*kdrmg*//**/n)/*g*/:/**/         
bitset_chan(n,false){/*rjk*/}/**//**//**/;bitset_chan(/*d*/int/*j*/n/**/,bool/**//**//*stb*/init/**//**/)/**//**/                                                    /*duq*/     /*iz*/                                                                                            /**/:n(n/*v*/),m(/**//**/         
/*petz*//**//*hw*//**//**//**//*q*//**//*mqr*//**//*zf*/(/*e*//**//**//*ta*/n+/**/B-/**/1)/**//**//B),/**/b/*g*/                                                    (m,init     ?~/*u*/                                                                                             /**/T(0/**/)/**/:T/*o*/(         
0)){trim/*t*//*x*/();}/**//**//*t*/;inline/*u*/void/*u*/set(int/**/i/**/,bool/**/val/**//**//**/)noexcept/*pc*/                                                   /*hzirzg     h*//**/                                                                                              /*npv*//**/{/**/assert(0         
/**//*ote*//*hh*//**//*dth*/<=i/*zw*//*s*/and/**//**/i/**//**/<n)/**/;/**//*p*/if/*a*/(/*oytl*/val/**/)b[i/*q*/   /B                                             /**/]|=/*     f*//**/                                       (                                                       /**/T/**//*p*/(/**/1)<<         
/*ij*//**//*h*//**//*n*//*qqv*//**//*ym*/(i/**/%/**//**/B));/**/else/**/b[i//**/B/**//*e*//*m*//**/]/*om*/&=~(                                               T (/*s*//**/     1)/**/<<                                       (i                                                      /*x*//**/%/**//*v*//**/         
B)/*wn*/);/**/}/**/inline/*o*/bool/*m*/get/**/(int/**/i)/**//**//**/const/*a*//**/noexcept{/**/assert/**//**/    (                                          0 /*aj*//**/     /*rlfjb*/                                      <=i                                                       /*giy*/and/**/i/**/<n)         
/*ij*//*zim*//*q*//**//*c*//**//*e*//*ze*//**//**//*i*//**//**//**//**//**//**//**//**/;return/*hd*/(b[/*knzl   */                                        i/B/**/]&(/**/     T(1/**/)                                       <<(i                                                      %B))/*et*/)!=/**/0/**/         
/*pzhl*//**//*ur*//**//**//*kbrmrc*//*gy*/;}/**//*d*//**//**/void/**/reset()noexcept/*a*/{/**/std::/*s*/fill    (                                        b/*lm*/.begin/*    ev*/(/**/                                       ),b.                                                       /*b*/end(),T/**//*e*/         
(0));}void operator&=(const bitset_chan&other){for(int i=0;i<std::min(m,other.m);i++)b[i]&=other.b[i];if(m> other                                          .m    )  std     ::fill(b.                                       begin                           () +other.   m,    b      .begin()+m,T(0));}void operator
|=(const/**/bitset_chan&other){/*u*/for/**//**/(int/**//*d*//**//**//*ut*/i=/**//**//**//**/0/**/;/**/i/**/ <                                         std::/*q*/min/*u       at*//**/                                       /*o*/                                                       (m/**//**/,/**/other         
/*ozy*//*ywokf*//*euksr*//**//**//*om*//**//*qhxrd*//**/./**//**//**//**//*zgf*/m);/**/i++)/*vuda*/b/*s*/[ i                                        /**/]/**/|=other/*g    f*/  ./**/                                       /**/b[                                                       i];trim();}/**//**/         
/**//**//**//**//*b*//**//**//*i*//*f*//*t*/void/**/operator^=/**/(const/**//*fd*//**//*i*/bitset_chan/**/                                         &/**/other){for(/**/    int/**/i=0                                       ;i<std                                                       /**/::min(/**/m/**/         
/*x*//*n*//**//**//**//**//**//*gy*//**//**/,/**//*h*/other./**/m/*b*/)/*u*/;/*j*/i++/**/)b/**/[/**/i/**/                                         ]^=other/**/.b[/**//*    dt*//*xc*/                                      i]/**/;                                                        /**/trim/**/()/**/         
/*zr*//**//**//*zy*//**//*lfz*//*hf*//**//**//*tx*//**//**//**//*a*/;/**/}/**/void/*gdva*/operator<<=/**/                                     (   int/*rmw*/x){if(/**/x    ==0)return                                      /*reoy*/                                                       ;if/**/(x>=/*y*/n)         
/**//*qdbrx*//**//*pf*//**//**//**//**//*t*//**//*f*//*g*//**//*d*//*ouz*/{reset();/*l*/return;/**/}/**/                                    /*j  sb*/const/**//**/int/*     jl*//*i*/                                           s=x /                                                      B,d=x%B,r=/*ijz*/         
/*dn*//*i*//*l*//**//**//*u*//**/B/**/-d;/**/if/*rn*/(/**//**//*v*/d>0)/**//**//**/{/**//*w*//**/for/**/                                   /* v *//**/(/*q*/int/**/i/**/   =m/**//**/     -                               1-/*p*/                                                          /**/s/**/;i>/*c*/         
/**//**//*rz*//*d*//**//*v*//*a*//*wlr*//**//**//**//**//**//*pd*//**/0;/**/i--/**/)b[/**/i/*r*//**/+s]=                                                (b/*t*//**//**/[   /*w*/i/*v*/                                    ]<<d)|/**/ (                                                      /*ud*/b/**/[/**/         
/**//*tg*//**//**//*p*//**//*xmy*//**//*pe*//*k*//**//**//*i*//**//**//*j*//**/i-/**/1]/**//**/>>/**/r)                                                     ;b[s/**/]/**/   =/**/b/**/   [                   0            ]<<d;}else {                                                      /*w*/for/**//**/         
/*de*//*sepg*//**//**//**//*b*//**//*m*//*f*//**/(int/**/i=/**//**/m/**//**/-1-/**/s/*l*//**//**/;i/**/                                                          >0;i--)   /*p*//**/b/*  */                  [            i/*k*/+/*t*/                                                   s   /*j*//**/]=/**/         
/*cyf*//**//*q*//*y*//**//**//*w*//*b*//*a*//*xlj*//**//*i*/b/**//*i*/[/**/i]/**/;/**/b/*v*//*f*/[/*y*/                                  s/*c*/]=b                  [/**/0  ]/**/;}std/* r*/                 /*           gk*/::fill(                                                     b  ./**//**/begin(         
/*ptr*//**//*f*//*j*/)/*j*/,b/**/.begin(/**//**/)/**//**/+s,T/**/(/**/0/**/))/**/;/**//**/trim/**//**/                                   /*wxdp*/           (         );/*n  t*/}/**//**/ void               /*            i*/operator                                                    /*  wps*//*bx*/>>=         
/*s*//**//*dwas*//*n*/(int/**/x/**//**//**/)/*d*//**//**//**/{/**/if(x/*h*/==0/*x*//**/)/**//**/return                                 ;  if/**/                        /*k*/(/**/x/*h*/>= n/*j               */         ) {reset()/**/                                                   ;/* t*//*h*/return         
/**//**//*gv*//**//**//*wfj*//**//*hhi*//**//*cx*//**/;/**//**//*u*/}const/*g*/int/*yi*/s/**//**/=x/B,                                 /*g*//*n*/                     d  /*i*/=/**/x%/**/B,l=B-d              /*h a      ho zl*/;/**/if     (                                             /*y  ge*//**//**/d         
/*zdj*//**//*h*//**//**//*zl*//*sfg*//*t*//*q*//**//*xz*//**//*thn*//*g*/>0/**/){for(int/**//*y*//**/              i                   /*ch*/=s/*k*//**/;/**/        i</**/m/**/-/**//**/1;/*h*/i/*c          bh*/ ++    )/* lbz*/b[i/*     */                                            /*lw */-s/*y*//**/         
/*st*//**//**//*hs*//*e*//*i*//*t*//*yg*//**//*ac*//**//**//**//**//*kcbe*//*l*//**//**//**//*yinuv*/                                  /*r*//**/]=/**//**//*a*/(/*v */b[i]/*q*//**/>>/**/d)|/**/(b[i/**//**/ /**//**/+1   ]/* bh*/<</*     dd*/                                            l);  b[/*k*/m/**/         
/*opn*//**//*f*//**//**//**//**//**//*q*//**//*zvmoamt*//*d*/-1/**/-s]=b/**//*d*//**/[m/**//**/-1/**/                                   ]>>d/**/;/**/}/**//*eh*/else/**/for/**//**//**//**//**//**/(int/**/i/*a*/                           =s;                                            i/*b uc*//**//**/         
/*rko*//*zs*//**//**//*fwc*//*p*//*vto*//**//*k*//**//**/<m;i/**/++/*r*//**/)b/**/[/*y*//*c*/i/*pa*/-              s                    /*wp*/]/**//**//**//**/=b/*n*/[/**/i]/**/;std/**//**/::fill/*t*//*i*/(                                                                             b./* p*/begin/**/         
/*yxi*//*baas*//**//**//*bak*//**//*nfrk*//*j*/(/*x*/)/**/+/**//*o*/m-s,/**/b/*z*//*cw*/.end(),T/**/                                     /*sm*//*w*//**/(0/**/)/**//*y*//*w*/)/**/;/**/}bool/**/operator/**//*         */           ==                                                      (/*c */const/**/         
/*t*//**//**//**/bitset_chan&other/**/){/**/return/**//**//*m*//**/(/**/(n/**/==/**//*u*/other/*j*/.                n                    /**/)and/*tv*/b/*z*/==other./**/b/**//**/);}/**//**/bool/**/operator                       /*m*/                                                   /*xl s*//**//**/         
!=/*v*/(/**//*k*/const/**/bitset_chan/**//*i*//**/&/**/other){return/**/!(/*g*/*/*j*//**/this==other                )                  ;  /*nng*/}bitset_chan/**//**/operator/*x*//**//**/&(const/**/bitset_chan/**/               /**//**/                                                 /*ivy ejfwctv*/&         
other){bitset_chan/**/result(*this)/**/;/*p*/result&=other/**/;/**//**/return/**//**//**/result/**/                 ;                  /*  cjygs*//**//*l*/}/**/bitset_chan/**/operator|/*a*//**//*t*/(const/**/bitset_chan       /*z*//**/                                                  /**/ /*h*/&/**/         
other){bitset_chan/**/result/*pf*/(*this)/**//*ob*/;/**//**/result/*l*/|=other/**/;return/**/result                                     /*s agop*/;}/**/bitset_chan/**//*qh*/operator/**/^/*q*//*yd*/(/**/const/**/bitset_chan   /*p*//*x   h*/                                            & /*qbkgovjuqli*/         
/*xy*//*he*//**//**//**//**//**/other/**/){/**/bitset_chan/**/result/**//**//**/(*this/**/);result                                      /**/^=/**//**/other/*vx*/;/**/return/**//*ep*/result/**//*u*/;}bitset_chan/**//*zp*//**/operator/**/>>                                             (  /**/ int/**/x)         
/*ap*//*fc*/{/**/bitset_chan/**//**/result/**/(/*r*//**/*this)/**//**/;result/*r*//*z*//**//**/>>=                                       x;/*o*/return/**/result/**//*x*/;}bitset_chan/**/operator/**/<<(/*r*/int/**/x/**//*q*/){bitset_chan                                               /* uh*/ /*x*//**/         
/*n*//*bxdn*//**//*f*//**//*o*//**//**//**/result(*/*y*/this/**/)/**//**//**/;/**/result/*v*/<<=x                                   ;    return/**/result/*dh*/;}/**//*q*/bitset_chan/**/operator/*k*/~/**//*z*/(){/**/bitset_chan/**/result(*                                             /*g mmu*//**/this         
/*hou*//*s*//*f*//**//*e*//**//**//**//*p*//**//*lz*//**//**/);/*k*/for(/**//*um*/auto/**/&v/*c*/                                   :  /* */result)/**/v/*l*/=~v/**/;/**//**//**/result.trim()/**//**//*h*//**/;return/**//**//**/result/**/                                                /* mmer*//*n*/;}         
/**//*vxv*//*n*//**//*o*//**//*tax*//**//**/int/**/count/**//*h*/()const/**//**//**/noexcept/**/                                    /* */{  return/**/std/**/::/**/accumulate(b./**//**//*b*/begin/**//**/(),b./**//**/end()/**//*g*//**/,                                                  /* *//* l*/0/**/         
/*rr*//*b*//**//*ab*//**//*x*//**//**//**//*ou*//**//*j*//*q*//*cya*/,[](/**/int/**//**/sum,/**/                                    /* wtz*//**/T/**//*ux*/value/*l*//*o*/)/**/{return/**/sum+popcnt(value/**/);/**/}/**/);}/**/int/**//*xe      */                                         /*vb*/find_first         
/*pry*//*dxni*//*v*//**//*sf*//*jh*//**//*d*//**//*q*//*f*//*h*//**//**//**//*sw*//**//*m*//**/                                      (  /*qyy*//*k*//*ce*/)/**//**/{int/**/pos=/**/-/**/1/**/;for(int/**//**//**/bi/**//**/=0/**/;bi</**/m       ;                                          /**/bi/**/++){if         
/**//*jf*//**//**//*z*//**//**//**//**//**//*pa*//*hpe*//**//*u*//*hg*//*ax*//*k*//**//*p*//**/                                       ( b[bi]==T/*h*/(0)/**//*   *//*t*/)/**//**/continue/**/;/*l*/pos/**/=ctz/**//**/(b/**//**/[bi/**//*       */                                           ])/*t*/+/**/bi*         
/*wkv*//**//*anqg*//**//*is*//**//*i*//*v*//*o*//**//**//*knh*//**/B;/**/break;}return/**/pos;                                          }int/*cj*/find_last/*a*/   /**/(/**//**/)/**/{/*x*//**/int/**//**/pos/**/=/**/-/**/1;for(/**//*    g*/int                                            /*l*/bi/*qgr*/=         
/*an*//**//*l*//**//*tl*//*w*//*uvuikagi*//**//**//**//**//*haz*//*mk*//*fr*/m/**//**/-1;bi>=                                            0/**//**/;/**/bi/*p*/--/*     su*//**/){/**/if(b/**/[/**/bi/**/]==T(/**/0))/*ws*/continue/**/   /*exw*/                                             /*vt*//*t*//**/         
/*s*//*e*//**//*icilsmi*//**//**//**//*e*//*ly*//*d*//**//**//*z*/;pos/**//**/=/**/B-clz/*y*/  (                                         /*fxvg*/b[bi/*z*//**/]/*f*/)-      1/**//**/+bi/**//**/*B/**//**//*fl*/;break/*p*//*r*/;}/* */return                                                 /*ou*/pos/**/;         
}/*im*//*r*/void/**/range_process(int/**//*k*/l/**/,int/*qb*/r,/**/auto/**/block_brute/**//*  */                                           ,auto/**//**/block_quick){assert                        /*nz*/(/*h*/0/**//**/<=/*i*/l/*  h*/and                                                    /*wt*/ l/**/<=         
/*jj*//*tyua*//**//*y*//*gwvi*//**//*w*//**//**//*if*//*mb*//*s*//*hyo*//*f*/r/*b*/and/**/r  <n                                              /**/);/**/int/**/bl=block_id(l)/**//*h*/      ,/**/br/**//**/=/**/block_id/**/(/**/   r);                                                        if/**/ /**/(bl         
/*l*//**//**//*p*//*b*//*w*//**//*p*//*lf*//**//**//*i*/==br/**/)/**/block_brute(/*lh*/l,/* */r                                                /*tl*//**/);/**//*x*//**//*ta*/else{block_brute(l/**//*s*/,/*biq*//**/(bl+/*b*/                                                           1)    /**/* B-1/**/         
)/*qya*/;/**/for/**//**/(/**//*t*//**//**/int/**/bi/**/=bl+/*z*//**/1;bi/**//*co*/</*jod*/ br;                                                   bi/*j*//*g*/++/**//**/)/*coci*//**/block_quick(bi/**/)/*l*/;/**/block_brute                                                              (    /*cim f*//**/         
br*B/*ipe*/,/**/r)/**//**/;}}/**//**/void/*b*//**/range_set(int/**/l,/**/int/**//**/r/*ke  */,                                                      /**/bool/*i*//**//**/val)/**/{/**//**/auto/**/block_brute/**//**//**/                                                                 /*    jqvu *//**/=         
/**//*j*//*o*//**/[/**/&/**//**/]/**//**/(/**/int/**/l/**//**/,int/**/r/**/)->void{/**//* p*/                                                   int   /*uh*//**/bi=block_id/**/(/**/l/**//**/)/**//**/;T/*o*/mask/**/=                                                                    /*y   *//* */range         
(l-bi*B+1,r-bi*B+1);if(val)b[bi]|=mask;else b[bi]&=~mask;};auto block_quick=[&](int bi)->void                                              {  b [bi]=( val?~T(0):T(0));};range_process(l,r,block_brute,block_quick                                                  )  ;}int  count (int  l,int  r){int cnt=    0;   
/*dmv*//*c*//**//*j*//**/auto/**/block_brute/**/=[/**/&/**//**/](/*vi*/int/**/l/**//*l*/,int                                                    /*ctmpt*/   r)->void/**/{cnt+=popcnt/*b*//**//**//**//**//**/                                                                              /*q   oh r*/(/**/         
/**//*m*//*o*//*e*//**//*m*//**//*d*//**//*ky*//*uqb*/submask(/**/l/**//**/,/*r*/r/**/));};                                                     /**/auto/**/   /*o*/block_quick/**/=[/**//**/&](/**/int                                                                                    /*sv   a d*/bi)->         
/*ym*//**/void/**/{/*y*/cnt/*q*/+=popcnt(/**/b[bi/*my*/]/*x*/);/**/};/**/range_process/**/                                                      /*h*//**/(l,/*    wm*/r,block_brute/**//**//**/                                                                                            /*cl   i pwqhvg*/         
,block_quick);return/*qx*/cnt;/**//**/}int/**//**/find_first(/**//**/int/**/l/**/,int/*d*/                                                      /*bi*/r/**/)/**/{    /*r*//**//*o*/int                                                                                                      /**/    pos=/**/         
/*p*//**//*ljom*/-/**/1;auto/**/block_brute=[/**/&/*l*/](int/**/l/**/,/**/int/**/r/**/)->                                                       /**/void/**//**//**/                                 {                                                                                      /*y*/   for/**/(         
/*gecng*//**//*i*//**//*s*//**//*o*//**//**//*k*/int/**//**/i=l;i<=r/**//**/and/**/pos==                                                        -1;i++)/**//*f*/if/*u*/                         /*pn*/                                                                                       /*x s  o*/(get(         
/*o*//**//**//*qy*//**//**//*d*//**/i))pos/**/=i;/*nx*/};auto/**/block_quick=[&/**//**/                                                         /**//*s*/]/**//**/(/**//**/                int/*z*/bi                                          )                                             ->/*   gw*/void         
/*c*//*l*//**//*m*//*qd*//**/{/**/if/**/(b/**/[/*l*/bi/**//**//**//*f*//**/]/**/==/**/T                                                         (0)or/*o*/pos!=/**//**/-1/**//**//**/)/*v*/return/**/                                          ;                                              /*h    qm*/pos         
/**//*v*//**//**//*t*//**//**//**//**//*q*//*e*//*u*//**//*wk*//*s*//*ke*/=/**/ctz/**/                                                         (b/**/[/*g*/bi])+/**/bi/**/*B;}/*d*/;range_process/**/                                           (                                             l/* */ ,r/**/,         
block_brute,block_quick);return/*rcuj*//**/pos/*w*/;/**//**//**//**/}int/**/find_last                                                          /**//**/(int/**//**/l/**//*j*/,/**/int/**//**//**/r/**/       )                                                                                 {  int /**/pos        
/*f*//*miycg*/=/*y*/-1;/**/auto/**/block_brute/**/=/**/[/*c*/&/**//*j*/]/**/(/*o cl*/                                                         int/**/l/**/,/*s*/int/**//**/r/**//*u*//**//**/)->void/*       */                    {                                                              for /*mr*/         
/*esnz*//**//**//*ockp*//*wobkf*//*ci*//**//**//**/(/*q*//**//*j*//**//**/int/* f*/i                                                         =l/*z*/;i/**/<=/*mr*/r/**/;i/**/++)/**/if/**//*k*//**/(get       (                    i                                                            )  )/* */pos         
=i/*nw*//**//**//**/;/*x*/}/*jp*/;auto/**/block_quick/**//**/=/**//**/[/**/&]/* s*/                                                         /**//**//*q*/(/*z*/int/**/bi)/*ji*/->void/**/{/**//**//**//*      */                   if(                                                          b  /*g cde*/         
/*ciop*//**//*h*//*k*//*lzd*//*a*//*krd*//**//**//**//*m*//*dr*//*tjy*//*b*//* v*/                                             /*s*/       [bi]==T/**//**//**/(/*y*/0)/**/)/**/return;/**/pos=B-clz/**//**/    ( b                  [ bi                                                       ]   /*x ubh*/         
/*cdg*//**//*vut*//*wbwp*//*gl*/)/**/-1/*sf*//**/+bi*/**/B/**/;/**//**/}/**//* */               ;                                         range_process/*s*/(l/**/,r/**//*vvs*/,/**/block_brute/**/,block_quick/* b      jr    *//*wv*//*nq*/                                                  )   ;/* mbz*/         
return pos;}friend std::ostream&operator<<(std::ostream&os,const bitset_chan&bitset                                        ) {for(int i =bitset.m-1;i>=0;--i)os<<std::bitset<B>(bitset.b[i]);os<<'\n';return os;}};using bitset_chan64=bitset_chan                                                 <uint64_t       , 
/*nuiu*//*j*//*t*//**//**//*g*//**//**//*zn*//**//*hw*//**//*n*/bit_width/**/ (                                                  /*dld     f fmph*//*g*//**//**//**//*es*//**//**//*tl*//*oric*//*zj*//*esufcqvx*//*dd*//*  *//**//**/uint64_t                   ( /*b  hywwwgs*/  )               /*u cty*/         
/*krk*//**//*lm*//**//**//*x*//**//**//**//*v*//*d*//**//**//**//*l*//**//**/                       /*  r*/                       /*rxb    utg*//*wss*//**//*c*//**//*l*//**//**//*ni*//**//**//**//*eox*//*fw*//**//**/ /**//*mxo*//*b*//*k*/ )                  /**/  /**//**//*d*/>;             /* evv*/         
/*oj*//*m*//*lj*//**//**//**//*b*//*l*//*ck*//**//*kw*//**//**//*u*//**//*qg          sj*//*t*/   /**/  /**/                   /* k*//*     s*//*bna*//**//**//*n*//**//*k*//*rl*//*czjru*//*ud*//*f*//*s*//**//*p*/   /*hovtxb*//**//**//**/                    /*q*/  /**//**//**//**//*u            diw*/         
